# Generated by Django 4.1.4 on 2023-01-26 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_profile_dark_mode'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='password_recovery_token',
            field=models.TextField(blank=True),
        ),
    ]
